### ISSUE TITLE
Is the example made for session or jwt?

### ISSUE THREAD

**Issue by federicosan** [node-casbin/express-authz#5]
I don't understand this part

https://github.com/node-casbin/express-authz/blob/f26ab2fe2c218ef0f97b5fbaf2e74e5d465c114a/test/server.js#L21-L26

Are you just trying to get the logged in username, why saving it to `req.user` and not `req.locals.user` or `req.locals.currentUser`?

**Comment by hsluoyz** [comment]
Hi @federicosan ,

This is because in the authz plugin, we assume the the username is stored in ``req.user`` and Casbin enforcer will read it. You can modify the following ``getUserName()`` function to get the username string from anywhere you like.

https://github.com/node-casbin/express-authz/blob/e43c0f16294c691eb945e331e332dc7e544065df/authz.js#L41-L48

**Comment by federicosan** [comment]
Hi @hsluoyz, thank you for your reply. I am not that experienced in express but it seems the express-way to pass around data between middleware is to use req.locals, see it here -> https://expressjs.com/es/api.html#res.locals

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
Hi @federicosan , we have a PR to solve this issue: https://github.com/node-casbin/express-authz/pull/6

Is it what you want?

**Comment by federicosan** [comment]
@hsluoyz Sorry for the delay, yes that's it!

**Comment by hsluoyz** [comment]
Nice. Close this issue now..
